### ISSUE TITLE
Session stores require @classic

### ISSUE THREAD

**Issue by maxwondercorn** [mainmatter/ember-simple-auth#2267]
Session stores extend from the Ember object so you do need the `@classic` decorator when using native class syntax.

This should be documented in the README. If you like, I can create a PR.

**Comment by gzurbach** [comment]
@marcoow Is there a way to avoid using `@classic` when extending the Cookie store?

```js
import classic from 'ember-classic-decorator';
import Cookie from 'ember-simple-auth/session-stores/cookie';

@classic
export default class ApplicationSessionStore extends Cookie {}
```

There is an ongoing issue in `ember-classic-decorator` (https://github.com/emberjs/ember-classic-decorator/pull/83) preventing apps to upgrade to Ember 4. 

And I can't remove `ember-classic-decorator` from my app as long as `ember-simple-auth` requires it.

Any suggestion would be greatly appreciated, thanks!

**Comment by maxwondercorn** [comment]
The fix for ember-classic-decorator [#83](https://github.com/emberjs/ember-classic-decorator/pull/83) has been fixed and merged so this is no longer a blocker to Ember 4.

**Comment by gzurbach** [comment]
I am in the process of updating our app to `ember-simple-auth@6.0.0`. Lots of good stuff in there!

I was wondering if I could remove the `@classic` decorator from my `ApplicationSessionStore`, but it seems like it's still necessary?

The app crashes with this error message in the console:

> Error: You defined the class ApplicationSessionStore that extends from EmberObject using native class syntax, but you didn't mark it with the @classic decorator. All user classes that extend from this class must be marked as @classic, since they use classic features. If you want to remove the @classic decorator, you must remove the base class. For components, you can do this by converting to Glimmer components. For plain classes that extend from EmberObject, you can convert them into plain native classes that do not extend from EmberObject.

The code triggering this error:

```js
import Cookie from 'ember-simple-auth/session-stores/cookie';

export default class ApplicationSessionStore extends Cookie {
  cookieExpirationTime = 30 * 24 * 60 * 60;
}
```

Are there any plans to convert classes from EmberObject to native classes at some point? This is the last `@classic` decorator left in the app :)

A big thank you to the maintainers for your hard work!

**Comment by gzurbach** [comment]
**Update**: we managed to remove the `@classic` decorator and successfully upgrade our app to Ember 5.8 without any problems. The app has been in production for a few weeks now, and we haven’t encountered any issues.

Previously, removing the `@classic` decorator would cause an error (as mentioned above), but it looks like Ember is now more flexible with extending from `EmberObject` using native class syntax. 🤷‍♂️

With that said, I believe we can close this issue @maxwondercorn.

**Comment by BobrImperator** [comment]
I forgot to check ban on this issue :pensive: but I'm glad it worked finally.

I'll close this issue, but feel free to report if there's still issues.
