### ISSUE TITLE
Breaking changes in 3.1

### ISSUE THREAD

**Issue by ef4** [mainmatter/ember-simple-auth#2280]
It seems that we experienced breaking changes when upgrading from 3.0 to 3.1.

This app did not use any of the route mixins, and handled all transitions on its own (we did not rely on ember-simple-auth triggering any transitions).

When trying to upgrade to 3.1, the test suite detected breakage because ember-simple-auth started issuing routing transitions that were unexpected.

Am I missing something I was supposed to do? Were those transitions supposed to be happening on 3.0 as well, but weren't for some reason? 

We can eventually refactor to use this newer pattern, but had to roll back the upgrade until we can.

**Comment by pabloascarza** [comment]
Same here we have some unexpected route transitions to the authentication route, we didn't experience this transitions using mixins in the 3.1.0beta.

**Comment by BobrImperator** [comment]
Is this still an issue?

**Comment by ef4** [comment]
I can no longer reproduce this on ember-simple-auth 4.2.2.
