### ISSUE TITLE
Migrate Mocha to Qunit

### ISSUE THREAD

**Issue by BobrImperator** [mainmatter/ember-simple-auth#2316]
We should migrate tests to use Qunit instead of Mocha.
Qunit is more standardized in the community, also ember-mocha is not actively maintained which is causing issues with embroider builds. While embroider could potentially be fixed in mocha, we believe that Qunit will be more appealing for people who'd want to chip in into development of ESA.

closes #2242

**Comment by brunoocasali** [comment]
@BobrImperator how do you pretend to start this? Create an initial PR with setup, them appending multiple other PR's with the refactorings?

If you do the setup I could help rewriting these specs ;)

**Comment by BobrImperator** [comment]
I was thinking about doing simply a big 💥  since the work is actually quite simple for the most part. I'd need to see how we could split the work if you're interested in helping out.

**Comment by brunoocasali** [comment]
Yes I am! hacktoberfest is closer 👯. We could create a big PR at the end, but multiple small PRs that merge into the big one...
Probably will be easier to review.

**Comment by BobrImperator** [comment]
closed by https://github.com/mainmatter/ember-simple-auth/pull/2330
