### ISSUE TITLE
Access token does not persist

### ISSUE THREAD

**Issue by PelePeluche** [mainmatter/ember-simple-auth#2468]
I am using ember-simple-auth with Fastboot. The logging part is working, or at least I get the token, but when I do a refresh I lose that token. How do I make it persistent?

I created the following file (I understand it's what the ember-simple-auth doc says)

`import CookieStore from 'ember-simple-auth/session-stores/cookie'
export default class ApplicationSessionStore extends CookieStore {}`

And this is the function I use to authenticate the user in my loggin component

   @action
   async authenticate (event) {
      event.preventDefault()
  
      const credentials = {
        email: this.email,
        password: this.password
      }
  
      try {
        await this.session.authenticate(AUTHENTICATOR, credentials)
        const expirationTime = 14 * 24 * 60 * 60
        this.session.store.cookieExpirationTime =  expirationTime
      } catch (error) {
        throw new FormSubmitError(error.json.errors[0].message)
      }
    }

**Comment by BobrImperator** [comment]
I think that this is the same issue as https://github.com/mainmatter/ember-simple-auth/issues/2410.

Could you please check that out and let us know later?
