### ISSUE TITLE
Incompatible with Ember 5.0.0 

### ISSUE THREAD

**Issue by Elawphant** [mainmatter/ember-simple-auth#2577]
Ember-simple-auth 5.0.0 is incompatible with ember-cli 5.0.0
it requires ember source 3.8 || 4, while ember-cli 5's ember-source is ~5.0.0 
If we `npm install ember-simple-auth --force` it will install it, but the browser will raise missing imports errors. e.g. Could not find module `@ember/polyfills` imported from `ember-simple-auth/utils/assign`.

**Comment by BobrImperator** [comment]
Please use `6.0.0-rc.1` version.
It should be fairly safe to use and soon we'll do an official `6.0.0` release.
I don't expect any library changes between the release candidate and `6.0.0` either.

**Comment by BobrImperator** [comment]
Link to the https://github.com/mainmatter/ember-simple-auth/releases/tag/6.0.0-rc.1

**Comment by Elawphant** [comment]
I can confirm that 6.0.0-rc.1 works fine. Looking forward to the release.

**Comment by bracke** [comment]
I'm getting "Could not find module `ember-simple-auth/services/session` imported from `(require)`" when using "6.0.0-rc.1".

This is with Ember 5 and embroider.

**Comment by BobrImperator** [comment]
Hi @bracke Are you using Torii by any chance?

**Comment by bracke** [comment]
@BobrImperator No, not in this project.
Anything I can do to locate the cause?

**Comment by BobrImperator** [comment]
@bracke It's a tricky issue.
Usually I'd find it to be a mixture of outdated addons and ember's build dependencies `ember-cli-babel`, `ember-auto-import`, `ember-resolver`.

However it could also be some issue with ESA not being an actual V2 addon.
I'll try to give it a shot later this week and setup a reproduction.

**Comment by bracke** [comment]
@BobrImperator the error happens in our session service when importing the basesessionservice, are we doing anything wrong?

```js
import { service } from '@ember/service';
import BaseSessionService from 'ember-simple-auth/services/session';

export default class SessionService extends BaseSessionService {
  @service currentUser;
  @service router;

  async handleAuthentication() {
    super.handleAuthentication(...arguments);

    try {
      await this.currentUser.load();
    } catch (err) {
      await this.invalidate();
    }
  }
}
```

**Comment by BobrImperator** [comment]
Thanks for the snippet.
It looks OK.

**Comment by bracke** [comment]
@BobrImperator 
I have now tried to run our tests and there I get the same problem:

`Could not find module `ember-simple-auth/test-support` imported from `(require)``

So the problem is really a general inability to access the 'ember-simple-auth' namespace/folder.

**Comment by bracke** [comment]
Hi @BobrImperator 

Did you get any further? Any idea how we can resolve this?

**Comment by BobrImperator** [comment]
It's very likely it's happening because ESA is still a V1 addon and V1 addons can't be statically analyzed.

WIP https://github.com/mainmatter/ember-simple-auth/pull/2604

**Comment by bracke** [comment]
I have tried to use the "v2-addon" branch, but it does not seem to make any difference.
I still get "Could not find module `ember-simple-auth/services/session` imported from `(require)`".

**Comment by BobrImperator** [comment]
The branch might not be functioning properly yet.

Also I've seen on some threads that a lot of folks are downgrading their @embroider deps to `3.0.0` because the current latest `3.1` introduced something that caused breakage:
```json
             "@embroider/core": "~3.0.0",
              "@embroider/compat": "~3.0.0",
              "@embroider/webpack": "~3.0.0",
 ```
 
 Like  Nullvox proposed to do here https://github.com/mainmatter/ember-simple-auth/pull/2606/files#diff-c88af450d41d3281997faafe7ac13e280ae5840c6b81f68cc395c2a20d7e4830R154
 Which didn't actually fix our CI but gave different errors.
 
 What embroider version are you using?

**Comment by bracke** [comment]
Still does not seem to change anything. 
I have tried all the things you mention.
Note: This is with Ember 5.1.2. and with embroider fully activated.

![billede](https://github.com/mainmatter/ember-simple-auth/assets/627383/d8840932-e2e0-4a29-a1a3-ccddeaab399b)

**Comment by RobbieTheWagner** [comment]
I'm getting ember-cookies errors myself

```
Build Error (PackagerRunner) in services/cookies.js

Module not found: Error: Can't resolve '/Users/rwwagner90/shipshape/swach/node_modules/.pnpm/ember-cookies@1.0.0/node_modules/ember-cookies/services/cookies' in '$TMPDIR/embroider/57a24f/services/cookies.js'
```

**Comment by RobbieTheWagner** [comment]
Seems that updating embroider fixes that for me.

**Comment by BobrImperator** [comment]
Ember-simple-auth 6.0.0 released
https://github.com/mainmatter/ember-simple-auth/blob/master/CHANGELOG.md#600-2023-08-18

Sorry for keeping you waiting :)
