### ISSUE TITLE
idea: consider no longer re-exporting anything in app

### ISSUE THREAD

**Issue by runspired** [mainmatter/ember-simple-auth#2810]
Since it is fairly common to extend the session service within an app, the re-export is both unneeded and in many build setups results in indeterminant service resolution during build when the app uses `session.ts` instead of `session.js`

**Comment by BobrImperator** [comment]
Great timing for the suggestion as I'm planning to make some breaking changes.

AFAIK that's what `ember-data` also does in newer versions - where you're required to import it yourself, but I'd like to ask. 

What about initializers?
Would you expect users to import them themselves?
Or is it a time to come up with an implementation that doesn't rely on them?

**Comment by BobrImperator** [comment]
closed by #2895
